name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code base
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check out code base
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: File configurations
      run: |
        echo '${{ secrets.BUSTER_SECRET }}' > misc/secrets.json

    - name: Run demo
      run: |
        make demo

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: starter
        path: |
          extensions/*
          !extensions/**/secret.json
          installed-extensions.png
          starter
